"""add_videos_table

Revision ID: bdb60d10063b
Revises: a7fdcd8fc487
Create Date: 2026-02-24 14:45:54.265052+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb60d10063b'
down_revision: Union[str, None] = 'a7fdcd8fc487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.Enum('uploaded', 'processing', 'done', 'error', name='video_status_enum'), nullable=False),
    sa.Column('frames_extracted', sa.Integer(), nullable=False),
    sa.Column('dive_session_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dive_session_id'], ['dive_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
