"""add_shark_main_photo

Revision ID: 8276b5d3215f
Revises: 2c4500f11d60
Create Date: 2026-02-24 13:40:18.639032+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8276b5d3215f'
down_revision: Union[str, None] = '2c4500f11d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharks', sa.Column('main_photo_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_sharks_main_photo', 'sharks', 'photos', ['main_photo_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sharks_main_photo', 'sharks', type_='foreignkey')
    op.drop_column('sharks', 'main_photo_id')
    # ### end Alembic commands ###
