"""add_photo_auto_detected

Revision ID: a7fdcd8fc487
Revises: 8276b5d3215f
Create Date: 2026-02-24 14:17:37.763165+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fdcd8fc487'
down_revision: Union[str, None] = '8276b5d3215f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('auto_detected', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'auto_detected')
    # ### end Alembic commands ###
