"""add_photo_annotation_fields

Revision ID: 2c4500f11d60
Revises: 073fb80f9ea2
Create Date: 2026-02-24 12:45:37.179995+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4500f11d60'
down_revision: Union[str, None] = '073fb80f9ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('shark_bbox', sa.JSON(), nullable=True))
    op.add_column('photos', sa.Column('zone_bbox', sa.JSON(), nullable=True))
    op.add_column('photos', sa.Column('orientation', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'orientation')
    op.drop_column('photos', 'zone_bbox')
    op.drop_column('photos', 'shark_bbox')
    # ### end Alembic commands ###
